[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
hello_world_anchor = "HPPStQ5VnPZr4BNJ53FYukBezuu9r5B5zMuJEJHSbKWR"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/im/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
